version: '3'
services:
  flask-backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"

  react-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/cert:/etc/nginx/cert
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - flask-backend
  #     - react-frontend
